-- Privacy-conscious ZiZu usage analytics.
-- Question and answer text are intentionally not stored.
create table if not exists public.zizu_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  category text not null default 'general',
  status text not null check (status in ('success', 'failed')),
  model text,
  latency_ms integer,
  input_tokens integer,
  output_tokens integer,
  error_code text,
  created_at timestamptz not null default now()
);

create index if not exists zizu_usage_created_at_idx
  on public.zizu_usage (created_at desc);
create index if not exists zizu_usage_user_id_idx
  on public.zizu_usage (user_id);

alter table public.zizu_usage enable row level security;

-- No browser policies: only trusted server/service-role code can access analytics.
revoke all on table public.zizu_usage from anon, authenticated;

